name: "custom_model"

backend: "custom_backend"

max_batch_size: 8

# input tensor
input [
  {
    name: "INPUT0"
    # note to self: switch to B16 after initial implementation
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]

# output tensor 
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
